### ISSUE TITLE
java.net.UnknownHostException: nifinode-6cc66886c7-qmfpj: Name or service not known during pod restart

### ISSUE THREAD

**Issue by anandkannachikandy** [AlexsJones/kubernetes-nifi-cluster#12]
Hi Alex,

Have you tried to delete one of the pods and wait for the pods to come-up again?
I tried this and got an unknown host exception since, after the pod got deleted and recreated, it gets a new host name.

Any Suggestions?

PFB, the error trace:

2019-03-20 05:36:38,325 WARN [Replicate Request Thread-8] o.a.n.c.c.h.r.ThreadPoolRequestReplicator Failed to replicate request GET /nifi-api/flow/current-user to nifinode-6cc66886c7-qmfpj:8080 due to java.net.UnknownHostException: nifinode-6cc66886c7-qmfpj: Name or service not known
2019-03-20 05:36:38,325 WARN [Replicate Request Thread-8] o.a.n.c.c.h.r.ThreadPoolRequestReplicator
java.net.UnknownHostException: nifinode-6cc66886c7-qmfpj: Name or service not known
        at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
        at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929)
        at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324)
        at java.net.InetAddress.getAllByName0(InetAddress.java:1277)
        at java.net.InetAddress.getAllByName(InetAddress.java:1193)
        at java.net.InetAddress.getAllByName(InetAddress.java:1127)
        at okhttp3.Dns$1.lookup(Dns.java:40)
        at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:185)

**Comment by AlexsJones** [comment]
The first thing I am unsure of is `nifinode-6cc66886c7-qmfpj:8080` that hostname looks completely wrong, it's a statefulset so shouldnt have that hostname suffix.

Can you give me a simple repro sequence? 
I assume it's deploy, delete a pod and see this error?

**Comment by anandkannachikandy** [comment]
Yes, the repro sequence is deploy, delete a pod and load nifi ui again. Let me check about the hostname issue

**Comment by anandkannachikandy** [comment]
Hi Alex , sorry for the trouble, this error happened in another setup of mine , it is an experimental setup.
